# Generated by Django 6.0.2 on 2026-05-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_user_task_due_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='google_calendar_event_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
